[connection]
address = "0.0.0.0"
port = 12345

[changes]
saving-commands = ["bp","bb"]
auto-save = true
auto-save-time = 90

[time]
time-sync = 30
start-time = 640

[white-list]
white-list = false
allowed-ips = [
    "127.0.0.1"
]

[world]
generator="base:demo"
seed=123

[content-packs]
allowed = [
    "base:0.25",
    "fmp:2.0"
]

[permissions]
ops = [
    "127.0.0.1"
]
